const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const script=html.split('<script>')[1].split('</script>')[0];
new vm.Script(script);
const core=script.slice(0,script.indexOf('const uid='));
const context={};vm.createContext(context);vm.runInContext(core+';this.check=validate;this.overlap=overlap;this.manual=manualSession;this.localTime=localTime;this.addBreak=addBreak;this.removeSession=removeSession;this.employee=createEmployee;this.normalize=normalizeTimeText;this.removeCustomer=removeCustomer;this.exportBackup=exportBackup;',context);
const data={version:1,customers:[{id:'c1',name:'Example'}],sessions:[{id:'s1',customer:'c1',start:1000,end:5000}],active:{customer:'c1',start:6000}};
assert.equal(context.check(JSON.parse(JSON.stringify(data))).active.start,6000);
assert.deepEqual(JSON.parse(JSON.stringify(context.check(data))),data);
const withComment={...data,sessions:[{...data.sessions[0],comment:'Kundmöte <script>är vanlig text</script>\nUppföljning.'}]};
assert.deepEqual(JSON.parse(JSON.stringify(context.check(JSON.parse(JSON.stringify(withComment))))),withComment);
assert.equal(context.check({...data,sessions:[{...data.sessions[0],comment:''}]}).sessions[0].comment,'');
for(const comment of [null,3,{},'x'.repeat(2001)])assert.throws(()=>context.check({...data,sessions:[{...data.sessions[0],comment}]}));
assert.equal(context.check({...data,sessions:[{...data.sessions[0],comment:'x'.repeat(2000)}]}).sessions[0].comment.length,2000);
for(const bad of [{...data,version:2},{...data,customers:[...data.customers,...data.customers]},
 {...data,active:{customer:'unknown',start:1}},{...data,sessions:[{...data.sessions[0],end:0}]},
 {...data,sessions:[{...data.sessions[0],start:NaN}]}, {...data,sessions:[...data.sessions,...data.sessions]}])assert.throws(()=>context.check(bad));
assert.equal(context.overlap({start:100,end:500},200,400),200);
assert.equal(context.overlap({start:100,end:500},600,800),0);
const midnight=new Date(2026,9,8).getTime();
const cross={start:midnight-3600000,end:midnight+3600000};
assert.equal(context.overlap(cross,midnight-86400000,midnight),3600000);
assert.equal(context.overlap(cross,midnight,midnight+86400000),3600000);
const manual={id:'manual',customer:'c1',start:5000,end:6000,comment:'Efterregistrerat'};
assert.equal(context.manual(data,manual).sessions.length,2);
assert.equal(data.sessions.length,1);
assert.equal(context.check(JSON.parse(JSON.stringify(context.manual(data,manual)))).sessions[1].comment,'Efterregistrerat');
for(const changes of [{start:2000,end:4000},{start:6000,end:7000},{start:5000,end:5000},{start:5000,end:4000},{customer:'missing'}])assert.throws(()=>context.manual(data,{...manual,...changes}));
const another={...data,customers:[...data.customers,{id:'c2',name:'Other'}]};
assert.equal(context.manual(another,{...manual,customer:'c2',start:2000,end:4000}).sessions.length,2);
for(const invalid of ['','2026-02-30T12:00','2026-10-08T24:01','2026-10-08T12:00Z'])assert.throws(()=>context.localTime(invalid));
assert.equal(context.localTime('2026-10-08T12:30'),+new Date(2026,9,8,12,30));
const paused=context.addBreak(data,'s1',{start:2000,end:3000});
assert.equal(context.overlap(paused.sessions[0],1000,5000),3000);
assert.equal(data.sessions[0].breaks,undefined);
assert.deepEqual(JSON.parse(JSON.stringify(context.check(JSON.parse(JSON.stringify(paused))))),JSON.parse(JSON.stringify(paused)));
const two=context.addBreak(paused,'s1',{start:3000,end:4000});
assert.equal(context.overlap(two.sessions[0],1000,5000),2000);
for(const pause of [{start:500,end:2000},{start:4000,end:6000},{start:2000,end:2000},{start:2500,end:3500},{start:2000,end:3000},{start:NaN,end:3000}])assert.throws(()=>context.addBreak(paused,'s1',pause));
assert.throws(()=>context.addBreak(paused,'missing',{start:2000,end:3000}));
assert.throws(()=>context.check({...data,sessions:[{...data.sessions[0],breaks:'bad'}]}));
assert.throws(()=>context.manual(paused,{...manual,start:2000,end:3000}));
const crossPause={...cross,breaks:[{start:midnight-1800000,end:midnight+1800000}]};
assert.equal(context.overlap(crossPause,midnight-86400000,midnight),1800000);
assert.equal(context.overlap(crossPause,midnight,midnight+86400000),1800000);
assert.equal(context.overlap(crossPause,midnight-86400000,midnight+86400000),3600000);
const twoSessions=context.manual(paused,manual),removed=context.removeSession(twoSessions,'s1');
assert.deepEqual(JSON.parse(JSON.stringify(removed.sessions)),[manual]);
assert.deepEqual(JSON.parse(JSON.stringify(removed.customers)),data.customers);
assert.deepEqual(JSON.parse(JSON.stringify(removed.active)),data.active);
assert.equal(twoSessions.sessions.length,2);
assert.equal(context.check(JSON.parse(JSON.stringify(removed))).sessions.length,1);
assert.throws(()=>context.removeSession(twoSessions,'missing'));
const employees=context.employee(context.employee(data,'0012'),'0013');
assert.deepEqual(JSON.parse(JSON.stringify(employees.employees)),['0012','0013']);
assert.equal(data.employees,undefined);
assert.throws(()=>context.employee(employees,'0012'));
for(const number of ['', 'abc', '12:3', '1'.repeat(21)])assert.throws(()=>context.employee(data,number));
const assigned={...employees,active:null,sessions:[{...data.sessions[0],employee:'0012'}]};
assert.deepEqual(JSON.parse(JSON.stringify(context.check(JSON.parse(JSON.stringify(assigned))))),JSON.parse(JSON.stringify(assigned)));
assert.throws(()=>context.check({...assigned,sessions:[{...assigned.sessions[0],employee:'missing'}]}));
const assignedOther={...assigned,customers:[...assigned.customers,{id:'c2',name:'Other'}]};
assert.throws(()=>context.manual(assignedOther,{...manual,employee:'0012',customer:'c2',start:2000,end:3000}));
assert.equal(context.manual(assigned,{...manual,employee:'0013',start:2000,end:3000}).sessions.length,2);
for(const [input,expected] of [['0930','09:30'],['930','09:30'],['9','09:00'],['17','17:00'],['0000','00:00'],['2359','23:59'],[' 09:30 ','09:30'],['2460','2460'],['9pm','9pm']])assert.equal(context.normalize(input),expected);
console.log('PASS: syntax, legacy/comment/pause backups, manual-time and pause conflicts, local dates and cross-midnight net totals');

const customerData={...withComment,customers:[...data.customers,{id:'c2',name:'Keep'}],sessions:[...withComment.sessions,{id:'s2',customer:'c2',start:20,end:30,comment:'Keep me'}],active:{customer:'c2',start:50}};
for(const token of ['', 'delete', 'DELETE '])assert.throws(()=>context.removeCustomer(customerData,'c1',token));
assert.throws(()=>context.removeCustomer(customerData,'c2','DELETE'));
assert.throws(()=>context.removeCustomer(customerData,'missing','DELETE'));
const deleted=context.removeCustomer(customerData,'c1','DELETE');
assert.equal(deleted.customers.length,1);assert.equal(deleted.customers[0].id,'c2');
assert.equal(deleted.sessions.length,1);assert.equal(deleted.sessions[0].comment,'Keep me');
assert.equal(deleted.active.customer,'c2');assert.equal(customerData.sessions.length,2);
const exported=context.exportBackup(customerData,new Date('2026-10-09T00:00:00Z'));
assert.equal(exported.exportedAt,'2026-10-09T00:00:00.000Z');
assert.equal(exported.sessions[0].comment,withComment.sessions[0].comment);
assert.deepEqual(JSON.parse(JSON.stringify(context.check(exported))),customerData);
console.log('PASS: typed customer deletion, active-pass protection, dated comment backup and import');